### ISSUE TITLE
Failure in Automated Tests via GitHub Actions

### ISSUE THREAD

**Issue by shinokaro** [Largo/ocran#14]
I have noticed that our automated tests through GitHub Actions are failing. Upon reviewing the logs, a specific error has been identified as the cause.

**Error Details**
```
C:/hostedtoolcache/windows/Ruby/3.3.0/x64/lib/ruby/3.3.0/pathname.rb:534:in `relative_path_from': different prefix: "D:/" and "C:/Users/RUNNER~1/AppData/Local/Temp/.ocrantest-2784-620605354/stdoutredir" (ArgumentError)
```
This error occurs when attempting to calculate relative paths between different drives in a Windows environment. Specifically, the `Pathname#relative_path_from` method is failing to compute the relative path between a path on the D: drive and a path on the C: drive.

### Proposed Solution
To resolve this issue, we need to adjust the environment settings in GitHub Actions to ensure that tests and scripts execute on the same drive. This may involve configuring GitHub Actions settings to enforce execution on a single drive.

If anyone has additional suggestions or approaches to address this problem, your feedback is highly appreciated.

**Comment by Largo** [comment]
I couldnt find the solution last time I checked. Maybe we have to overwrite the function. I think there might have been a fix in an older version of ocran? 
if the problem is also in ruby, we should open a bug issue on the ruby tracker

**Comment by shinokaro** [comment]
I will take on this issue. 
This problem is specific to Windows due to the use of drive letters, and occurs when the application's development environment spans multiple drives.

**Comment by Largo** [comment]
Thank you!
@shinokaro will you come to rubykaigi?

**Comment by shinokaro** [comment]
@Largo 
 I will not go to Rubykaigi.

**Comment by shinokaro** [comment]
The error from Pathname doesn't seem to be an issue with test_ocra.rb, as I'm getting it when running stub.
It turns out that this error occurs in Ruby 3,2 and later.

**Comment by shinokaro** [comment]
It seems that the problem can be solved by changing the bundler version to 2.4.22.

**Comment by shinokaro** [comment]
The cause of the error we encountered was reported in Bundler.
https://github.com/rubygems/rubygems/pull/5128
I solved the problem by increasing the version of Bundler.

Another issue is causing the automated test to fail. I'll work on this.

**Comment by shinokaro** [comment]
```
Finished in 101.184307s, 0.5040 runs/s, 2.0952 assertions/s.
  1) Failure:
TestOcran#test_rubyopt [D:/a/ocran/ocran/test/test_ocra.rb:578]:
Expected: "-rtime"
  Actual: "-rC:/hostedtoolcache/windows/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/bundler-2.4.22/lib/bundler/setup -rtime"
  2) Failure:
TestOcran#test_rubyopt_manual [D:/a/ocran/ocran/test/test_ocra.rb:594]:
Expected false to be truthy.
  3) Failure:
TestOcran#test_gemfile [D:/a/ocran/ocran/test/test_ocra.rb:216]:
Expected false to be truthy.
51 runs, 212 assertions, 3 failures, 0 errors, 0 skips
```
https://github.com/Largo/ocran/actions/runs/9016794292/job/24774085861

We got to the point where 3 tests failed.

**Comment by shinokaro** [comment]
Since Ruby 3.2, `bundle exec` seems to give `-rC:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/setup`.

**Comment by shinokaro** [comment]
When you use bundle exec to run your code, Bundler sets the RUBYOPT environment variable to `-rbundler/setup`. Until Ruby 3.1, this was a relative path, but from Ruby 3.2 it will be set to an absolute path (e.g. `-rC:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/setup`).
This change is due to the fact that in Ruby 3.2 and later, Bundler has been built into RubyGems.

**Comment by shinokaro** [comment]
Past successful tests did not use 'bundle exec'.
I'm thinking of passing the test with 'bundle exec' in use.
I'm fixing 3 tests that are failing, but I'm trying to figure out how to fix them without changing the meaning of the tests.

**Comment by shinokaro** [comment]
https://github.com/Largo/ocran/commit/f287ca2d1869fcb90f67677e9a1e77aaf5ab3ae4
This commit resolved the failure of TestOcran#test_rubyopt_manual.

**Comment by Largo** [comment]
Thanks! That is very useful :)

**Comment by shinokaro** [comment]
To resolve the two test failures, we need to consider how to handle the -r option in RUBYOPT. When an absolute path to bundler/setup is provided, should OCRAN attempt to convert it to its own path? This is because the absolute path includes the bundler version. Alternatively, should we remove the absolute path to bundler/setup?

The stub can handle absolute paths in the stub execution environment. The issue arises when there is a space in the Windows username, resulting in an installation path with spaces.

We cannot pass a path with spaces in the RUBYOPT environment variable. Generally, when providing a path with spaces as an argument or environment variable, we enclose the path in double quotes. This method works when passing arguments to Ruby. However, when doing the same for the RUBYOPT environment variable, it does not work in Ruby. Ruby interprets the double quotes as part of the path string in the RUBYOPT environment variable.

Another method for this scenario, enclosing both the option character (-r) and the path in double quotes, works in Ruby 3.2 but fails in Ruby 3.3.

Here are the potential solutions for handling an absolute path with spaces to bundler/setup in the -r option set in RUBYOPT:

1. Rewrite it to a relative path (-rbundler/setup) -> `require': cannot load such file
2. Replace the absolute path with the stub execution environment's absolute path and enclose it in double quotes -> fails only in Ruby 3.3
3. Remove it and do nothing.
4. Remove it and transfer it to Ruby's startup options.

I will investigate what is happening in Ruby 3.3.

**Comment by shinokaro** [comment]
```
>set RUBYOPT=-r"time" & ruby -v -e "p Time.now.iso8601" 
ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x64-mingw-ucrt]
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- "time" (LoadError)
Did you mean?  time
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'

```

```
>set RUBYOPT="-rtime" & ruby -v -e "p Time.now.iso8601" 
ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x64-mingw-ucrt]
-e:1:in `<main>': undefined method `iso8601' for 2024-05-16 22:06:22.5403023 +0900:Time (NoMethodError)

```

As of Ruby 3.2, RUBYOPT has no way to give -r a path that contains spaces. What we can infer from this is that all Ruby to date has not been able to give a path that contains spaces to RUBYOPT.

**Comment by shinokaro** [comment]
The temporary solution is "remove the absolute path from RUBYOPT to bundler/setup and do nothing".
I commit this method to get the test passed.
In other words, it reproduces "OCRA" instead of "OCRAN".

**Comment by shinokaro** [comment]
https://github.com/Largo/ocran/commit/07cf38351a7f2f08cbf74f51fd6fc102d9c5298a
This commit resolved the failure of TestOcran#test_rubyopt.

This causes all tests to pass, but the problem still remains.
A warning statement is output from TestOcran#test_gemfile.

**Comment by shinokaro** [comment]
This commit was able to silence the warning from TestOcran#test_gemfile.

**Comment by shinokaro** [comment]
https://github.com/Largo/ocran/issues/20
